# Generated by Django 5.1.5 on 2025-02-22 20:20

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_admin_chatroom_groupchat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='message',
            name='context',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сообщение'),
        ),
    ]
